FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Trip Share

It is simple application to share your ride.

### Verify Phone Number [Post]

It is  verifying phone number after taking it and returning response as verified or not.

+ Request (application/json)

        {
            "phone_number" : 0212121
        }
        
+ Response 200 (application/json)
 
     
    + Body

            {
                "response" : {
                    "response_status" : 200,
                    "response_message" : "Successful"
                }
            }

### Phone Number Authentication [POST]

This is for authenticating phone number while signing up in the app. 

+ Request (application/json)

        {
            "auth_code" : “sda23r34”

        }

+ Response 200 (application/json)

If phone number exists, then response 200_OK and redirect to sign up to create a new user

    + Body

            {
                
                "response" : {
                   " response_status " : 200
                   " response_message " : " authenticated "
                    
            
                         } 
            }
            
+ Response 201 (application/json)

If phone number exists and has done signup already, then return user information. 

    + Body

            {
                "data" : {
                    "user" : {}
                
                },
                "response" : {
                   " response_status " : 200
                   " response_message " : " Authenticated "
                    
            
                         } 
            }
            
### Sign Up [POST]

This is for an unregistered user to sign up for a new account with a verified phone number.

+ Request (application/json)

    + Attributes
        + phone_number (string, required)
        + full_name (string, required)
        + email (string, optional)
        + company_email (string, optional)
        + license_number (string, optional)
        + country_code (string, required)
        + fb_id (string, optional)
        + birth_date (string, required)
        + license_number (string, optional)
        + profile_pic (byte[], optional)
        + gender (string, required)
        
        
    + Body
    
            {
                "phone_number" : "01735528397"
                "full_name" : " shuvo champ "
                "email" : "nightshuvo@gmail.com"
                "company_email" : "shuvo@bracits.com"
                "license_number" : "46sa4f86as4fg65wa4f6wa"
                "country_code" : "565"
                "fb_id" : "65sa4d65as4d6w4d6w"
                "birth_date" : "2/3/5689"
                "license_number" : "4d6s5a4d6as46a"
                "profile_pic" : "7w9q8e76a5s4d"
                "gender" : "male"
            }

+ Response 200 (application/json)

   

    + Body
    
            {
                "data" : {
                        "user" : {}
                    
                    },
                "response" : {
                       "response_status" : 200
                       "response_message" : "authenticated"
                             } 
            }
            
#############Rahin starts 16th Oct,2018#########

### View profile[Get]

This is for viewing the profile of any user(how it looks like, what data it contains)

+ Headers {
    "api_key" : "Token ddsgdsggff"
        }
        
+ Request (application/json)
    {
        "user_id" : "74564"
        "trip_id" : "76438"
        
    }

    

+ Response 200 (application/json)

    + Body
    
        {
            "user_id" : "74564",
            "profile_pic" : "url",
            "full_name" : "utshaw",
            "rating" :"4.5",
            "number_of_rides_taken" : "33",
            "number_of_rides_hosted" : "43",
            "completeness" : "80%"
            "is_license_number_verified" : true,
            "is_phone_number_verified" : true,
            "is_email_id_verified" : true,
            "is_facebook_verified" : true,
            "user_company" :
                {
                    "company_id" : "0393",
                    "is_currently_working" : true,
                    "joined" : "10 July 2018",
                }
            hosted_ratings_and_review:
                {
                    "from" : "utshaw",
                    "rating" : "4.5",
                    "review" : "Awesome",
                }
            error: {
                [
                    ]
            }
        }
            
            
### Update Profile[PUT] 

 This is for editing one's profile, for an overall change.
 
 + Headers
    {
        "api_key" : "Token cjhh"
    }
+ Request (application/json)

        {   
            "full_name" : "razib",
            "profile_pic" : "url",
            "fb_id" : "facebook.com/teekhikheer",
            "personal_email" : "meethachuri@apple.com",
            "birth_date" : "26.01.1900",
            "license_number" : "846398463905",
            "gender" : "male/female",
            "office_start_time" : "8:00",
            "office_end_time" : "16:00",
            "phone_number" : "01911232222",
            "vehicle_type" : "nissan",
            "country_code" : "BD-007",
            "home_address" : "hemayetpur",
            "user_company" : {
                "company_name" : "BITS",
                "company_email" : "bits@bracits.com",
                "company_address" : "niketan",
            }
        }
        
+ Response (application/json)
    
        { 
            "status" : "200",
            "message" : "successfully updated",
            "success" : true,
            "error" : {
                [
                    ]
                {
            "data" : { 
                        "full_name" : "razib",
                        "profile_pic" : "url",
                        "fb_id" : "facebook.com/teekhikheer",
                        "personal_email" : "meethachuri@apple.com",
                        "birth_date" : "26.01.1900",
                        "license_number" : "846398463905",
                        "gender" : "male/female",
                        "office_start_time" : "8:00",
                        "office_end_time" : "16:00",
                        "phone_number" : "01911232222",
                        "vehicle_type" : "nissan",
                        "country_code" : "BD-007",
                        "home_address" : "hemayetpur",
                        "user_company" : {
                            "company_name" : "BITS",
                            "company_email" : "bits@bracits.com",
                            "company_address" : "niketan",
                    }
                    
### Add request company[Post] 
            

            
















#############Rahin ends 16th Oct,2018#########


            
### License verification [POST]

This is for an unregistered user to sign up for a new account with a verified phone number.

+ Request (application/json)

    + Attributes
        + license_number (string, optional)
        
        
    + Body
    
            {
                "license_number" : "4d6s5a4d6as46a"
            }

+ Response 200 (application/json)

   

    + Body
    
            {
                "response" : {
                       "response_status" : 200
                       "response_message" : "valid"
                             } 
            }
            
+ Response 409 (application/json)

   Already exists license

    + Body
    
            {
                "response" : {
                       "response_status" : 409
                       "response_message" : "Already Exists"
                             } 
            }

+ Response 401 (application/json)

   Invalid license

    + Body
    
            {
                "response" : {
                       "response_status" : 401
                       "response_message" : "Invalid License"
                             } 
            }

            
### Logout User [POST]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
        }

+ Response 200 (application/json)

   

    + Body

            {
            "success": true
            "message": "Successfully logout you."
            }

### Find Trip [GET]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
            "time":"5:30 PM",
            "date":"2018-08-02",
            "vehicle_type":"car/cng/bike/any",
            "seat":"5",
            "source":"lat/lng",
            "destination":"lat/lng"
        }

+ Response 200 (application/json)

   

    + Body

            [{
            "results": {
                "from":"niketan",
                "to":"uttara",
                "time":"12:30",
                "date":"2018-09-09",
                "price_per_seat":"123",
                "user":{
                    "full_name":"raju mazumder",
                    "rating":"4.5",
                    "number_of_rides":"4"
                }
              },
              "count": 100,
              "next":"2",
              "prev":"1"
            }]
            
### Trip Details [GET]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
            "trip_id":"898jjhh"
        }

+ Response 200 (application/json)

   

    + Body

           {
            "host": {
                "profile_pic":"url",
                "full_name":"raju mazumder",
                "rating":"4.5",
                "number_of_rides":"4",
                "is_phone_number_verified": true,
                "is_email_address":true
                "is_company_name": true,
                "joining_date": "2018-09-09",
                "reviews":[{
                    "desc": "test review",
                    "date": "2018-09-09",
                    "rating": "4.5",
                    "reviewer":{
                        "profile_pic": "url",
                        "full_name": "raju mazumder"
                    }
                }],
                "is_friend": true,
                "send_friend_request": true,
                "mutual_friends": [
                        {
                            "full_name": "raju mazumder"
                            }
                        ]
            },
            "members":
                [{
                    "profile_pic":"url",
                    "first_name":"raju"
                }],
            "number_of_seat":4,
            "price_per_seat":130,
            "vehicle_type": "car",
            "empty_seat": "4",
            "amenities":{
                "is_smoking": true,
                "is_music": true,
                "is_ac": true
            },
            "time": "4:50 PM",
            "date": "2018-09-09"
           }
           
### Triper Details [GET]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
            "trip_id":"898jjhh"
        }

+ Response 200 (application/json)

   

    + Body

           {
                "profile_pic":"url",
                "full_name":"raju mazumder",
                "rating":"4.5",
                "number_of_rides":"4",
                "is_phone_number_verified": true,
                "is_email_address":true
                "is_company_name": true,
                "joining_date": "2018-09-09",
                "reviews":[{
                    "desc": "test review",
                    "date": "2018-09-09",
                    "rating": "4.5",
                    "reviewer":{
                        "profile_pic": "url",
                        "full_name": "raju mazumder"
                    }
                }],
                "is_friend": true,
                "send_friend_request": true,
                "mutual_friends": [
                        {
                            "full_name": "raju mazumder"
                            }
                        ]
            }
            
      
            



### View amenities [Put]
user : admin,regular
+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
           "user_id" : "4as5d4a6"

        }

+ Response 200 (application/json)

   

    + Body

            {
            "data" : { 
            "amenities" : [{
            "amenity_id" : "4as5d4a6"
            "amenity_name" : "Baby_on_board"
            "status" : "true";
            }],
            },
           
            "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfully added",
            "error" : [{}]
            }
           
            }
            



### Add amenities [Post]
user : admin
+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
           "amenity_name" : "Baby_on_board"

        }

+ Response 200 (application/json)

   

    + Body

            {
            
             "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfully added",
            "error" : [{}]
          
            }
            

+ Response 409 (application/json)

   

    + Body

            {
           
             "response" : { 
            "status" : "409",
            "success": "false",
            "message": "Already Exists",
            "error" : [{"msg":"aminity name already exists"}]
            }

### Hide amenities [Put]
user : admin
+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
            "amenity_id" : "4as5d4a6"
            "amenity_name" : "Baby_on_board"
            "status" : "true";
        }

+ Response 200 (application/json)

   

    + Body

            {
            "success": true,
            "message": "Successfully modified"
            },
            

### Create Trip [POST]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
            "data" : {
            "trip" : {
             "time":"4:50 PM",
            "date":"2018-09-09",
            "from": "niketan",
            "to": "uttara",
            "vehicle_type": "car",
            "personal": "yes/no",
            "is_ac": true,
            "is_music": true,
            "is_smoking": true,
            "number_of_seat": "4",
            "price_per_seat": "120",
            "accept_auto": true,
            "need_confirmation": true
            },
            
            "amenities" : [
            {
            "amenity_id" : "1"
            },
            {
            "amenity_id" : "2"
            },
            ]
            
            },
           
            
        }

+ Response 200 (application/json)

   

    + Body

            {
            "success": true,
            "message": "Successfully created"
            }
                        


### Edit Trip [Put]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
            "data" : {
            "trip" : {
            "trip_id" : "a5sd69a6s",
             "time":"4:50 PM",
            "date":"2018-09-09",
            "from": "niketan",
            "to": "uttara",
            "vehicle_type": "car",
            "personal": "yes/no",
            "is_ac": true,
            "is_music": true,
            "is_smoking": true,
            "number_of_seat": "4",
            "price_per_seat": "120",
            "accept_auto": true,
            "need_confirmation": true
            },
            
            "amenities" : [
            {
            "amenity_id" : "1"
            },
            {
            "amenity_id" : "2"
            },
            ]
            
            },
           
            
        }

+ Response 200 (application/json)

   

    + Body

            {
            
            "data" : {},
            
                                     "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfully modified",
            "error" : [{}]
            }

+ Response 412 (application/json)

   

    + Body

            {
            
            "data" : {},
            
        "response" : { 
            "status" : "412",
            "success": "false",
            "message": "precondition Failed",
            "error" : [{
            "msg" : "can't edit a already started trip"
            }]
            }



### View All Trip Requests [Get]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    },
+ Request (application/json)

        {
            "trip_id" : "4as5d4a6"
            "host_id" : "Baby_on_board"
            "status" : "ontrie";
        },

+ Response 200 (application/json)

   

    + Body

            {
            "data" : {
             "trip_requests" : [{
            "request_id" : "d4as6d4as",
            "user_id" : "das4d6wa",
            "user_fullname" : "rafin",
            "company_name" : "Bits",
            "user_review" : "4.5",
            "no_of_rides_taken" : "45",
            "Source_location" : "lat/lon",
            "source_location_name" : "niketon",
            "destination_location" : "lat/lon",
            "destination_location_name" : "mohakali",
            "status" : "pending"
            }]
            },
           
            
           
             "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfully Added",
            "error" : [{}]
            },
[Socket]            
### View Coming Trip Request [Put]

user : admin
+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    };
+ Request (application/json)

        {
            "trip_id" : "4as5d4a6"
            "Request_id" : "Baby_on_board"
            "status" : "ontrie";
        },

+ Response 200 (application/json)

   

    + Body

        {
            "data" : {
             "user" : {
            "user_id" : "das4d6wa",
            "user_fullname" : "rafin",
            "user_review" : "4.5",
            "no_of_rides_taken" : "45"
            "is_phone_varified" : "true",
            "is_email_verified" : "true",
            "is_company_verified" : "true",
             "company" : "Bits",
            },
           
            
            "Reviews" : [{
            "from_user_id" : "d4a6d4s"
            "from_user_fullname" : "khan"
            "review" : "very good",
            "rating" : "3.5"
            }],
            
            "trip_request" : {
            "request_id" : "d4sa6d46a"
            "Source_location" : "lat/lon",
            "source_location_name" : "niketon",
            "destination_location" : "lat/lon",
            "destination_location_name" : "mohakali",
            },
            
            "status" : "pending",
            },
           
             "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfully modified",
            "error" : [{}]
            },
           
          
            },
                
        },

### Accept/Decline Trip Request [Put]

user : trip_host
+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
            "user_id" : "4as5d4a6"
            "trip_request_id" : "d4as5d"
            "status" : "accept";
        },

+ Response 200 (application/json)

   

    + Body

        {
             "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfully done",
            "error" : [{}]
            },
            },    
           
        },
        

+ Response 401 (application/json)

   

    + Body

        {
             "response" : { 
            "status" : "401",
            "success": "false",
            "message": "Unauthorizad",
            "error" : [{}]
            },
            },    
           
        },
        
### See trip Map [Get]

+ Request (application/json)

        {
            "user_id" : "4as5d4a6"
            "trip_id" : "d4as5d"
        },


+ Response 200 (application/json)

   

    + Body

        {
        
            "trip_members" : [{
            "member_id" : "d4sa5d45a6s",
             "fullname" : "rahin"
            "profile_pic" : "f4s6df6sd"
            "pickup_location" : "lat/long",
            "pickip_loaction_name" : "niketon",
            "drop_location" : "lat_long";
            "drop_location_name" : "mohakhali",
            "final_drop_location" : "lat/lan",
            "final_drop_location_name" : "badda"
            "status" : "onroute"
            }],
            
           
            
             "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfull",
            "error" : [{}]
            },
           
        },

### End Trip[Put]

+ Request (application/json)

        {
            "user_id" : "4as5d4a6"
            "trip_id" : "d4as5d"
        },


+ Response 200 (application/json)

    + Body

        {
        
          "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfull",
            "error" : [{}]
            },
          
           
        },
        
+ Response 412 (application/json)

    + Body

        {
        
            "response" : { 
            "status" : "412",
            "success": "false",
            "message": "Precondition Failed",
            "error" : [{
            "msg" : "Can't end trip with trip members existing"
            }]
            },
           
        },

+ Response 401 (application/json)

    + Body

        {
        
           "response" : { 
            "status" : "401",
            "success": "false",
            "message": "Unauthorized",
            "error" : [{
            "msg" : "Only host can end trip"
            }]
            },
        },       
        
### Review and rating [post]

+ Request (application/json)

        {
            "from_id" : "4as5d4a6",
            "to_id" : "4as5d4a6",
            "trip_id" : "d4as5d"
            "rating" : "5",
            "review" : "veru good"
        },


+ Response 200 (application/json)

    + Body

        {
         "response" : { 
            "status" : "200",
            "success": "true",
            "message": "successful",
            "error" : [{}]
            },
         
          
        },
        

### Drop Rider [Put]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
            "user_id":"442355",
            "trip_id":"dsgid",
            "rider_id" : "4a6sd46asd46",
            "satus" : "dropped"
            
        }

+ Response 200 (application/json)

   

    + Body

           {
           
           "fare" : "30"
           
             {
                 "response" : { 
                    "status" : "200",
                    "success": "true",
                    "message": "successful",
                    "error" : [{}]
            },
           
           }
 
 
 
 
### Favourites [Get]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
            "user_id": "s23-234-234-234"
        }

+ Response 200 (application/json)

   

    + Body

            {
                "results" : [
                    { 
                        "name" : "Work",
                        "location" : "30.23423/23.23434",
                        "location_name" : "Brac IT Services"
                    },
                    { 
                        "name" : "Home",
                        "location" : "30.23423/23.23434",
                        "location_name" : "agargaon"
                    },
                    { 
                        "name" : "AIUB",
                        "location" : "30.23423/23.23434",
                        "location_name" : "American International University Bangladesh"
                    }
                ],
                "response" : {
                    "response_status" : 200,
                    "response_message" : "Successful"
                }
            }
            
### Create Favourites [Post]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
            "user_id": "s23-234-234-234",
            "favorite_place" : { 
                    "name" : "Work",
                    "location" : "30.23423/23.23434",
                    "location_name" : "Brac IT Services"
                }
        }

+ Response 200 (application/json)

   

    + Body

            {
                "favorite_place" : { 
                    "name" : "Work",
                    "location" : "30.23423/23.23434",
                    "location_name" : "Brac IT Services"
                },
                "response" : {
                    "response_status" : 200,
                    "response_message" : "Successful"
                }
            }
            
### Update Favourites [Put]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
            "user_id": "s23-234-234-234",
            "favorite_place" : { 
                    "favorites_id" : 2342
                    "name" : "Work",
                    "location" : "30.23423/23.23434",
                    "location_name" : "Brac IT Services"
                }
        }

+ Response 200 (application/json)

   

    + Body

            {
                "favorite_place" : {
                    "name" : "Work",
                    "location" : "30.23423/23.23434",
                    "location_name" : "Brac IT Services"
                },
                "response" : {
                    "response_status" : 200,
                    "response_message" : "Successful"
                }
            }
            
### Collection Of Companies [Get]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

+ Response 200 (application/json)

   

    + Body

            {
                "results" : [
                    { 
                        "company_id" : "2343",
                        "company_name" : "Brac Bank Ltd.",
                        "location_name" : "Anik Tower Niketan"
                    },
                    { 
                        "company_id" : "4356",
                        "company_name" : "Brac IT Services",
                        "location_name" : "Niketan"
                    }
                ],
                "response" : {
                    "response_status" : 200,
                    "response_message" : "Successful"
                }
            }
            
### Add a Company [Post]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
            "company_name" : "Brac Bank Ltd.",
            "phone_number" : 01676868564,
            "address" : "34/A niketan, dhaka",
            "location" : "30.23423/23.23434",
            "company_email" : "bits@bracits.com"
        }

+ Response 200 (application/json)

   

    + Body

            {
                "data" :{
                    "company_name" : "Brac Bank Ltd.",
                    "phone_number" : 01676868564,
                    "address" : "34/A niketan, dhaka",
                    "location" : "30.23423/23.23434",
                    "company_email" : "bits@bracits.com"
                },
                "response" : {
                    "response_status" : 200,
                    "response_message" : "Successful"
                }
            }
            
### View Pending Friend Request [Get]

Here user will see the list of pending friends request

+ Headers 
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
            "user_id" : "2637"
        }
        
+ Response 200 (application/json)

    + Body
    
            {
                "pending_list": [{
                    "user" : [{
                                "profile_pic":"url",
                                "full_name":"utshaw",
                                "rating":"4.5",
                            }]
                                }]
                        
                    "mutual_friends": [
                            {
                                "full_name": "raju mazumder"
                                }
                            ]
                        
            }