FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Trip Share

It is simple application to share your ride.

### Verify Phone Number [Post]

It is  verifying phone number after taking it and returning response as verified or not.

+ Request (application/json)

        {
            "phone_number" : 0212121
        }
        
+ Response 200 (application/json)
 
     
    + Body

            {
               "response" : {
                    "status" : 200,
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
            }
            
+ Response 400 (application/json)
 
     
    + Body

            {
               "response" : {
                    "status" : "400",
                    "message" : "Bad Request",
                    "success" : "false",
                    "error" : [{
                    "message" : "Invalid Phone Number"
                    }]
            }

+ Response 400 (application/json)
 
     
    + Body

            {
               "response" : {
                    "status" : "400",
                    "message" : "Successful",
                    "success" : "false",
                    "error" : [{
                    "message" : "Phone Number Doesn't Exist"
                    }]
            }


### Phone Number Authentication [POST]

This is for authenticating phone number while signing up in the app. 

+ Request (application/json)

    + Attributes
        + auth_code (string, required)
      
    + Body
    
            {
                "auth_code" : “sda23r34”
            }

+ Response 200 (application/json)

If phone number doesn't exist sign up to create a new user

    + Body

            {
                "data" : {
                    "user" : {},
                    },
                    
               "response" : {
                    "status" : "200",
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
            }
            
+ Response 201 (application/json)

If phone number exists and has done signup already, then return user information. 

    + Body

            {
                "data" : {
                "user_profile" : {
                "user_id" : "d4as867d9waq",
                "phone_number" : "01735528397",
                "full_name" : " shuvo champ ",
                "country_code" : "565",
                "profile_pic" : "url",
                "gender" : "male"
                        },
                "Favorites" : [{
                "user_id" : "dsa8d6as8",
                "name" : "hoime",
                "location" : "lat/lon",
                "location_name" : "banani 11"
                }]
                },
                     
               "response" : {
                    "status" : "200",
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                    },
            }
            
### Sign Up [POST]

This is for an unregistered user to sign up for a new account with a verified phone number.

+ Request (application/json)

    + Attributes
        + phone_number (string, required)
        + full_name (string, required)
        + email (string, optional)
        + company_email (string, optional)
        + license_number (string, optional)
        + country_code (string, required)
        + fb_id (string, optional)
        + birth_date (string, required)
        + license_number (string, optional)
        + profile_pic (byte[], optional)
        + gender (string, required)
        
        
+ Body
    
        {
            "phone_number" : "01735528397",
            "full_name" : " shuvo champ ",
            "email" : "nightshuvo@gmail.com",
            "company_email" : "shuvo@bracits.com",
            "license_number" : "46sa4f86as4fg65wa4f6wa",
            "country_code" : "565",
            "fb_id" : "65sa4d65as4d6w4d6w",
            "birth_date" : "2/3/5689",
            "license_number" : "4d6s5a4d6as46a",
            "profile_pic" : "7w9q8e76a5s4d",
            "gender" : "male"
        }

+ Response 200 (application/json)

   

    + Body
    
            {
                "data" : {
                "user_profile" : {
                "user_id" : "d4as867d9waq",
                "phone_number" : "01735528397",
                "full_name" : " shuvo champ ",
                "country_code" : "565",
                "profile_pic" : "url",
                "gender" : "male"
                        },
                "Favorites" : [{}]
                },
                    
                    },
               "response" : {
                    "status" : "200",
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                    },
            }
            

### View Host profile[Get]

This is for viewing the profile of host 

+ Headers {
    "api_key" : "Token ddsgdsggff"
        }
        
+ Request (application/json)
    {
        "host_id" : "74564",
        
    }

    

+ Response 200 (application/json)

    + Body
    
        {   "data" : {
            "user_profile" : {
             "user_id" : "74564",
            "profile_pic" : "url",
            "full_name" : "utshaw",
            "rating" :"4.5",
            "number_of_rides_taken" : "33",
            "number_of_rides_hosted" : "43",
            "completeness" : "80%"
            "is_license_number_verified" : true,
            "is_phone_number_verified" : true,
            "is_email_id_verified" : true,
            "is_facebook_verified" : true
            }
            "user_company" :
                {
                    "company_id" : "0393",
                    "company_name" : "google"
                    "is_currently_working" : true,
                    "joined" : "10 July 2018",
                }
            "rider_review_ratings":
                [{
                    "user" : {
                    "user_id" : "d46waw"
                    "fullname" : "utsahw",
                    }
                    "rating" : "4.5",
                    "review" : "Awesome",
                    "date" : "2/3/5846"
                }]
            }
           
          "response" : {
                    "status" : "200",
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                    },
        }
        
### View Rider profile[Get]

This is for viewing the profile of any rider

+ Headers {
    "api_key" : "Token ddsgdsggff"
        }
        
+ Request (application/json)
    {
        "user_id" : "74564"
    }

    

+ Response 200 (application/json)

    + Body
    
        {   
            "data" : {
                    "user_profile" : {
                        "user_id" : "74564",
                        "profile_pic" : "url",
                        "full_name" : "utshaw",
                        "rating" :"4.5",
                        "number_of_rides_taken" : "33",
                        "number_of_rides_hosted" : "43",
                        "completeness" : "80%"
                        "is_license_number_verified" : true,
                        "is_phone_number_verified" : true,
                        "is_email_id_verified" : true,
                        "is_facebook_verified" : true
                        },
                    "user_company" :
                        {
                            "company_id" : "0393",
                            "company_name" : "google"
                            "is_currently_working" : true,
                            "joined" : "10 July 2018",
                        },
                    "host_review_ratings":
                        [{
                            "user" : {
                            "user_id" : "d46waw"
                            "fullname" : "utsahw",
                            }
                            "rating" : "4.5",
                            "review" : "Awesome",
                            "date" : "2/3/5846"
                        }],
                    "rider_review_ratings":
                        [{
                            "user" : {
                            "user_id" : "d46waw"
                            "fullname" : "utsahw",
                            }
                            "rating" : "4.5",
                            "review" : "Awesome",
                            "date" : "2/3/5846"
                        }]
                    }
            
                error: { [] }
        }
            
### update Profile [PUT] 

 This is for editing one's profile, for an overall change.
 
 + Headers
    {
        "api_key" : "Token cjhh"
    }
+ Request (application/json)

        {   
            "full_name" : "razib",
            "profile_pic" : "url",
            "fb_id" : "facebook.com/teekhikheer",
            "personal_email" : "meethachuri@apple.com",
            "birth_date" : "26.01.1900",
            "gender" : "male/female",
            "office_start_time" : "8:00",
            "office_end_time" : "16:00",
            "country_code" : "BD-007",
           
        }

        
+ Response (application/json)
    
        { 
           
            "data" : { "user_id" : "hiou74564634",
                        "full_name" : "razib",
                        "profile_pic" : "url",
                        "fb_id" : "facebook.com/teekhikheer",
                        "personal_email" : "meethachuri@apple.com",
                        "birth_date" : "26.01.1900",
                        "gender" : "male/female",
                        "office_start_time" : "8:00",
                        "office_end_time" : "16:00",
                        "phone_number" : "01911232222",
                        "country_code" : "BD-007",
                        "joining_date" : "2/3/2015"
                         }
                         
                          "response" : {
                    "status" : "200",
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                    },
                         
                         }
                    
### Add request company [Post] 
            
This is for adding a company by an user if it doesn't exist in DB

+ Headers
    {
        "api_key" : "Token gfhjfh"
    }
    
+ Request (application/json)

        {
            "company_name" : "bits",
            "phone_number" : "01735680276",
            "address" : "Tejgaon Link Road",
            "location" : "lat/lng",
            "location_name" : "niketan/gulshan",
            "company_email" : "bits@bracits.com"
        }
        
+ Response 200 (application/json)

    + Body
    
            {
                "data" : {},
            
                 "response" : {
                    "status" : "200",
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                    },
            }
            
### View friend list [Get]

This is for the users to see their friends list, who are in the list

+ Headers
        { 
            "api_key" :"ghfxhgsf"
        }

+ Request (application/json)
    
        {
            "user_id" : "gfygf"
        }
        
+ Response 200 (application/json)

        {
            "data" : {
            "user" : [{
            "user_id" : "sdf654s65df",
            "fullname" : "raizd",
            "ratings" : "4.5",
            "no_of_rides_taken" : 56,
             "user_company" :
                {
                    "company_id" : "0393",
                    "company_name" : "google"
                    "is_currently_working" : true,
                    "joined" : "10 July 2018",
                },
            },
            {
            "user_id" : "sdf654s65df",
            "fullname" : "raizd",
            "ratings" : "4.5",
            "no_of_rides_taken" : 56,
             "user_company" :
                {
                    "company_id" : "0393",
                    "company_name" : "google"
                    "is_currently_working" : true,
                    "joined" : "10 July 2018",
                },
            }] ,
            },
           
           "response" : {
                    "status" : "200",
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                    },
            
        }
        
### User ride history[Get]

User can see the ride history according to types such as hosted, taken or both

+ Headers
    {
        "api_key" :"Token ghfsdhb"
    }
    
+ Request (application/json)
    
    {
        "user_id" : "78987",
       
    }
    
+ Response 200 (application/json)
    
    {
        "data" : {
            "trip_members" : 
            [{
            "trip_id" : "7e6wr6w",
            "pickup_location" : "lat/long",
            "pickup_location_name" : "niketon",
            "final_drop_location" : "lat/long",
            "final_drop_location_name" : "uttara",
            "join_time" : "4:30 2/8/2019",
            "fare" : "30"
            
            },
            {
            "trip_id" : "7e6wr6w",
            "pickup_location" : "lat/long",
            "pickup_location_name" : "niketon",
            "final_drop_location" : "lat/long",
            "final_drop_location_name" : "uttara",
            "join_time" : "4:30 2/8/2019",
            "fare" : "30"
            
            }],
        },
        "response" : {
            "status" : "200",
            "message" : "Successful",
            "success" : "true",
            "error" : [{}]
            },
    }
    
           
### User hosted ride history[Get]

User can see the ride history according to types such as hosted, taken or both

+ Headers
    {
        "api_key" :"Token ghfsdhb"
    }
    
+ Request (application/json)
    
    {
        "user_id" : "78987",
       
    }
    
+ Response 200 (application/json)
    

    {
      "data" : {
      "trip" : 
      [{
      "trip_id" : "7e6wr6w",
      "start_location" : "lat/long",
      "start_location_name" : "niketon",
      "final_end_location" : "lat/long",
      "final_end_location_name" : "uttara",
      "start_time" : "4:30 2/8/2019",
      "fare" : "30"
      },
      {
      "trip_id" : "7e6wr6w",
      "start_location" : "lat/long",
      "start_location_name" : "niketon",
      "final_end_location" : "lat/long",
      "final_end_location_name" : "uttara",
      "start_time" : "4:30 2/8/2019",
      "fare" : "30"
      }],
      
    "response" : {
                    "status" : "200",
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                    },
    }
    
    
### Facebook verification[Post]

+ Request (application/json)

    + Attributes
        + fb_id (string, required)
        
        
    + Body
    
            {
                "fb_id" : "4d6s5a4d6as46a"
                "user_id" : "d46aw"
            }

+ Response 200 (application/json)

   

    + Body
    
            {
            "data" : {},
            
                "response" : {
                    "status" : "200",
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                    },
            }
            
+ Response 409 (application/json)

   Already exists license

    + Body
    
            {
                 "response" : {
                    "status" : "409",
                    "message" : "Conflict",
                    "success" : "false",
                    "error" : [{
                    "message" : "fb_id already exists"}]
                    },
            }

+ Response 400 (application/json)

   Invalid fb_id

    + Body
    
            {
                 "response" : {
                    "status" : "400",
                    "message" : "Bad Request",
                    "success" : "false",
                    "error" : [{
                    "message" : "Id invalid"}]
                    },
            }
            
+ Response 404 (application/json)

   fb_id doesn't exist

    + Body
    
            {
                 "response" : {
                    "status" : "404",
                    "message" : "Not found",
                    "success" : "false",
                    "error" : [{
                    "message" : "Id  doesn't exist"}]
                    },
            }

           
            
### License verification [POST]

This is for an unregistered user to sign up for a new account with a verified phone number.

+ Request (application/json)

    + Attributes
        + license_number (string, optional)
        
        
    + Body
    
            {
                "license_number" : "4d6s5a4d6as46a"
                "user_id" : "d46aw"
            }

+ Response 200 (application/json)

   

    + Body
    
            {
            "data" : {},
            
                "response" : {
                    "status" : "200",
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                    },
            }
            
+ Response 409 (application/json)

   Already exists license

    + Body
    
            {
                 "response" : {
                    "status" : "409",
                    "message" : "Conflict",
                    "success" : "false",
                    "error" : [{
                    "message" : "license already exists"}]
                    },
            }

+ Response 400 (application/json)

   Invalid license

    + Body
    
            {
                 "response" : {
                    "status" : "400",
                    "message" : "Conflict",
                    "success" : "false",
                    "error" : [{
                    "message" : "license Invalid"}]
                    },
            }
            
+ Response 404 (application/json)

   license doesn't exist

    + Body
    
            {
                 "response" : {
                    "status" : "404",
                    "message" : "Not found",
                    "success" : "false",
                    "error" : [{
                    "message" : "license  doesn't exist"}]
                    },
            }


            
### Logout User [POST]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
        }

+ Response 200 (application/json)

   

    + Body

            {
                "response" : {
                        "status" : "200",
                        "message" : "Successfully Logged out ",
                        "success" : "true",
                        "error" : [{}]
                        },
            }

### Find Trip [GET]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
            "time":"5:30 PM",
            "date":"30-10-2018",
            "pickup_location":"lat/lng",
            "pickup_location_name" : "uttata"
            "seat":"5",
            "drop_location":"lat/lng",
            "drop_location_name":"mohakhali",
            "vehicle_type":"2"
            "amenities" : [
            {"amenity_id" : 2},
            {"amenity_id" : 1},
            {"amenity_id" : 3}
            ]

        }

+ Response 200 (application/json)

   

    + Body

            {
                "data" : {
                    "results": [
                        {
                                "start_location":"lat/lon",
                                "start_location_name":"niketan",
                                "end_location":"lat/lon",
                                "end_location_name":"uttara",
                                "start_time":"12:30 PM",
                                "date":"30-10-2018",
                                "price_per_seat":"123",
                                "user": {
                                    "user_id" : "e4rw654r3",
                                    "full_name":"raju mazumder",
                                    "rating":"4.5",
                                    "number_of_rides":"4",
                                    "profile_pic": "url",
                                    "phone_number": 016764650452
                                }
                        },
                        {
                                "start_location":"lat/lon",
                                "start_location_name":"niketan",
                                "end_location":"lat/lon",
                                "end_location_name":"uttara",
                                "start_time":"12:30 PM",
                                "date":"30-10-2018",
                                "price_per_seat":"123",
                                "user": {
                                    "user_id" : "e4rw654r3",
                                    "full_name":"raju mazumder",
                                    "rating":"4.5",
                                    "number_of_rides":"4",
                                    "profile_pic": "url",
                                    "phone_number": 016764650452
                                }
                        },
                    ],
                "count": 100,
                "next":"2",
                "prev":"1"
                },
                "response" : {
                        "status" : "200",
                        "success" : "true",
                        "message" : "Trip(s) Found",
                        "error" : [{}]
                    },
            }
            
### Trip Details [GET]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
            "trip_id":"898jjhh"
        }

+ Response 200 (application/json)

   

    + Body

           {
            "host": {
                "profile_pic":"url",
                "full_name":"raju mazumder",
                "rating":"4.5",
                "number_of_rides":"4",
                "is_phone_number_verified": true,
                "is_email_address":true
                "is_company_name": true,
                "joining_date": "2018-09-09",
                "reviews":[{
                    "desc": "test review",
                    "date": "2018-09-09",
                    "rating": "4.5",
                    "reviewer":{
                        "profile_pic": "url",
                        "full_name": "raju mazumder"
                    }
                }],
                "is_friend": true,
                "send_friend_request": true,
                "mutual_friends": [
                        {
                            "full_name": "raju mazumder"
                            }
                        ]
            },
            "members":
                [{
                    "profile_pic":"url",
                    "first_name":"raju"
                }],
            "number_of_seat":4,
            "price_per_seat":130,
            "vehicle_type": "car",
            "empty_seat": "4",
            "amenities":{
                "is_smoking": true,
                "is_music": true,
                "is_ac": true
            },
            "time": "4:50 PM",
            "date": "2018-09-09"
           }
 
        

### View amenities [Get]
user : regular
+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
           "user_id" : "4as5d4a6"

        }

+ Response 200 (application/json)

   

    + Body

            {
            "data" : { 
            "amenities" : [{
            "amenity_id" : "4as5d4a6"
            "amenity_name" : "Baby_on_board"
            "status" : "true";
            }],
            },
           
            "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfully",
            "error" : [{}]
            }
           
            }
            



### Add amenities [Post]
user : admin
+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
           "amenity_name" : "Baby_on_board"

        }

+ Response 200 (application/json)

   

    + Body

            {
            
             "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfully added",
            "error" : [{}]
          
            }
            

+ Response 409 (application/json)

   

    + Body

            {
           
             "response" : { 
            "status" : "409",
            "success": "false",
            "message": "Already Exists",
            "error" : [{"msg":"aminity name already exists"}]
            }

### Hide amenities [Put]
user : admin
+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
            "amenity_id" : "4as5d4a6"
            "amenity_name" : "Baby_on_board"
            "status" : "true";
        }

+ Response 200 (application/json)

   

    + Body

            {
            
            
            
             "response" : { 
            "status" : "200",
            "success": "true",
            "message": "successful",
            "error" : [{}]
            }
            },
            

### Create Trip [POST]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
            "time":"4:50 PM",
            "date":"2018-09-09",
            "start_location_name": "niketan",
            "start_location": "lat/lon",
            "end_location_name": "uttara",
            "end_location": "lat/lon",
            "vehicle_type": "2",
            "personal": "yes/no",
            "is_ac": true,
            "is_music": true,
            "is_smoking": true,
            "number_of_seat": "4",
            "price_per_seat": "120",
            "accept_auto": true,
            "need_confirmation": true,
            "amenities" : [
                {
                    "amenity_id" : "1"
                },
                {
                    "amenity_id" : "2"
                },
            ]
        }

+ Response 200 (application/json)

   

    + Body

            {
            
                "data" : {
                    "trip" : {
                        "trip_id" : "d54we68qw",
                        "time":"4:50 PM",
                        "date":"2018-09-09",
                        "start_location_name": "niketan",
                        "start_location": "lat/lon",
                        "end_location_name": "uttara",
                        "end_location": "lat/lon",
                        "vehicle_type": "2",
                        "personal": "yes/no",
                        "is_ac": true,
                        "is_music": true,
                        "is_smoking": true,
                        "number_of_seat": "4",
                        "number_of_seat_available": "1",
                        "price_per_seat": "120",
                        "accept_auto": true,
                        "need_confirmation": true,
                        "host": {
                            "user_id" : "sdf-sdf-sdfsdf-32sdf"
                            "full_name":"raju mazumder",
                        },
                        "status" : {
                            "id" : 23434,
                            "desc" : "Trip is ready",
                        }
                    },
                    "amenities" : [
                        {
                        "amenity_id" : "1"
                        },
                        {
                        "amenity_id" : "2"
                        },
                    ]
                },
                "response" : { 
                "status" : "200",
                "success": "true",
                "message": "Trip Has Been Created",
                "error" : [{}]
                }
            }

### Start Trip [PUT]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }

+ Request (application/json)

        {
           "trip_id" : "d486w564aw",
           "host_id" : "8e67rw8",
        }

+ Response 200 (application/json)

   

    + Body

            {
            
                "data" : {
                    "trip_id: "r4e6w",      
                    "status" : "onroute"
                    },
                "response" : { 
                    "status" : "200",
                    "success": "true",
                    "message": "Trip has been started",
                    "error" : [{}]
                    },
            }


+ Response 412 (application/json)

   

    + Body

            {
            
                "data" : {
                    "trip_id: "r4e6w",      
                    "status" : "not-onroute"
                },
                "response" : { 
                    "status" : "412",
                    "success": "false",
                    "message": "Trip is not started",
                    "error" : [{
                        "messsage" : "You need atleast one rider to start the trip"
                    }]
                },
            }
             

### Send Trip Request [POST]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }

+ Request (application/json)

        {
           "trip_id" : "d486w564aw",
           "user_id" : "8e67rw8",
          
        }

+ Response 200 (application/json)

   

    + Body

            {
            
                "data" : {
                    "trip_request" : {
                        "trip_request_id" : "fse545",
                        "trip_id: "r4e6w",      
                        "request_timedate" : "30-10-2018",
                        "status" : "not-onroute",
                        "source_location" : "lat/long",
                        "source_location_name" : "niketon",
                        "destination_location" : "lat/long",
                        "destination_location_name" : "mohakhali",
                        "number_of_seat" : 2
                        },
                    },
                "response" : { 
                    "status" : "200",
                    "success": "true",
                    "message": "Request is sent",
                    "error" : [{}]
                    },
            }


+ Response 412 (application/json)

   

    + Body

            {
            
                "data" : {
              
                },
            
            },
            
           
            
             "response" : { 
            "status" : "412",
            "success": "false",
            "message": "Precondition Failed",
            "error" : [{
            "message" : "Ride already started"
            }]
            },
            }


### Edit Trip [Put]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
          
            "trip_id" : "a5sd69a6s",
             "time":"4:50 PM",
            "date":"2018-09-09",
          "start_location_name": "niketan",
             "start_location": "lat/lon",
            "end_location_name": "uttara",
              "end_location": "lat/lon",
            "vehicle_type": "car",
            "personal": "yes/no",
            "is_ac": true,
            "is_music": true,
            "is_smoking": true,
            "number_of_seat": "4",
            "price_per_seat": "120",
            "accept_auto": true,
            "need_confirmation": true,
           
            "amenities" : [
            {
            "amenity_id" : "1"
            },
            {
            "amenity_id" : "2"
            },
            ]
            
           
           
            
        }

+ Response 200 (application/json)

   

    + Body

            {
            
            "data" : {},
            
                                     "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfully modified",
            "error" : [{}]
            }

+ Response 412 (application/json)

   

    + Body

            {
            
            "data" : {},
            
        "response" : { 
            "status" : "412",
            "success": "false",
            "message": "precondition Failed",
            "error" : [{
            "msg" : "can't edit a already started trip"
            }]
            }


### Cancel Trip [Put]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
          
            "trip_id" : "a5sd69a6s",
            "host_id" : "ad5wa9wq"
        }

+ Response 200 (application/json)

   

    + Body

            {
                "data" : {
                    "trip_id" : "a5sd69a6s",
                    "trip_status" : "cancelled"
                },
                
                "response" : { 
                "status" : "200",
                "success": "true",
                "message": "Trip is cancelled",
                "error" : [{}]
            }


+ Response 412 (application/json)

   

    + Body

            {
            
                "data" : {},
                
                "response" : { 
                    "status" : "412",
                    "success": "false",
                    "message": "Cannot cancel with members ontrip",
                    "error" : [{}]
                    }
            }

### View All Trip Requests [Get]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    },
+ Request (application/json)

        {
            "trip_id" : "4as5d4a6"
            "host_id" : "Baby_on_board"
           
        },

+ Response 200 (application/json)

   

    + Body

            {
            "data" : {
             "trip_requests" : [{
            "request_id" : "d4as6d4as",
            "user_id" : "das4d6wa",
            "user_fullname" : "rafin",
            "company_name" : "Bits",
            "user_review" : "4.5",
            "no_of_rides_taken" : "45",
            "Source_location" : "lat/lon",
            "source_location_name" : "niketon",
            "destination_location" : "lat/lon",
            "destination_location_name" : "mohakali",
            "status" : "pending"
            }]
            },
           
            
           
             "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfully Added",
            "error" : [{}]
            },
[Socket]            
### View Coming Trip Request [Put]

user : admin
+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    };
+ Request (application/json)

        {
            "trip_id" : "4as5d4a6"
            "Request_id" : "Baby_on_board"
            "status" : "ontrie";
        },

+ Response 200 (application/json)

   

    + Body

        {
            "data" : {
             "user" : {
            "user_id" : "das4d6wa",
            "user_fullname" : "rafin",
            "user_review" : "4.5",
            "no_of_rides_taken" : "45"
            "is_phone_varified" : "true",
            "is_email_verified" : "true",
            "is_company_verified" : "true",
             "company" : "Bits",
            },
           
            
            "Reviews" : [{
            "from_user_id" : "d4a6d4s"
            "from_user_fullname" : "khan"
            "review" : "very good",
            "rating" : "3.5"
            }],
            
            "trip_request" : {
            "request_id" : "d4sa6d46a"
            "Source_location" : "lat/lon",
            "source_location_name" : "niketon",
            "destination_location" : "lat/lon",
            "destination_location_name" : "mohakali",
            },
            
            "status" : "pending",
            },
           
             "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfully modified",
            "error" : [{}]
            },
           
          
            },
                
        },

### Accept/Decline Trip Request [Put]

user : trip_host
+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
            "user_id" : "4as5d4a6"
            "trip_request_id" : "d4as5d"
            "status" : "accept/decline";
        },

+ Response 200 (application/json)

   

    + Body

        {

        "data" : {},
             "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfully done",
            "error" : [{}]
            }    
           
        }
        
+ Response 401 (application/json)

    + Body

        {
            "response" : { 
            "status" : "401",
            "success": "false",
            "message": "No seat(s) available",
            "error" : [{}]
            },
            },    
           
        },


+ Response 428  (application/json)

   

    + Body

        {"data" : {},
             "response" : { 
            "status" : "428",
            "success": "false",
            "message": "Precondition Failed",
            "error" : [{
            "message" : "Rider Cancelled request",
            }]
            },
            },    
           
        },
    
+ Response 409  (application/json)

   

    + Body

        {"data" : {},
             "response" : { 
            "status" : "409",
            "success": "false",
            "message": "Conflict",
            "error" : [{
            "message" : "Request Already Accepted",
            }]
            },
            },    
           
        },
   

+ Response 401 (application/json)

   

    + Body

        {"data" : {},
             "response" : { 
            "status" : "401",
            "success": "false",
            "message": "Unauthorizad",
            "error" : [{
            "message" : "Not Allowed",
            }]
            },
            },    
           
        },
        <!--
### View Trip [Get]

+ Request (application/json)

        {
            "user_id" : "4as5d4a6"
            "trip_id" : "d4as5d"
        },


+ Response 200 (application/json)

   

    + Body

        {
        
            "trip_members" : [{
            "member_id" : "d4sa5d45a6s",
            "fullname" : "rahin"
            "profile_pic" : "f4s6df6sd"
            "pickup_location" : "lat/long",
            "pickip_loaction_name" : "niketon",
            "drop_location" : "lat_long";
            "drop_location_name" : "mohakhali",
            "final_drop_location" : "lat/lan",
            "final_drop_location_name" : "badda"
            "status" : "onroute"
            }],
            
           
            
             "response" : { 
            "status" : "200",
            "success": "true",
            "message": "Successfull",
            "error" : [{}]
            },
           
        },
-->
### End Trip[Put]

+ Request (application/json)

        {
            "host_id" : "4as5d4a6"
            "trip_id" : "d4as5d"
        },


+ Response 200 (application/json)

    + Body

        {
        
            "data" : {
                "total_earning" : 564,
                "rating" : 5,
                "trip_members" :[
                    {
                        "user_id" : "4fewr6",
                        "full_name" : "hasan",
                        "pay_amount" : 45
                    }
                ]

            },
            "response" : { 
                "status" : "200",
                "success": "true",
                "message": "Tris has been ended",
                "error" : [{}]
                },
        },
        
+ Response 412 (application/json)

    + Body

        {
            "response" : { 
                "status" : "412",
                "success": "false",
                "message": "Precondition Failed",
                "error" : [
                    {
                        "message" : "Can't end trip with trip members on trip status"
                    }
                ]
            },
        }

+ Response 401 (application/json)

    + Body

        {
        
           "response" : { 
                "status" : "401",
                "success": "false",
                "message": "Unauthorized",
                "error" : [
                    {
                        "message" : "Only host can end trip"
                    }
                ]
            },
        }       
        
### Give Review and rating [post]

+ Request (application/json)

        {
            "from_id" : "user_id",
            "to_id" : "host_id",
            "trip_id" : "d4as5d",
            "rating" : "5",
            "review" : "very good"
        },


+ Response 200 (application/json)

    + Body

        {
            "data" : {
                
            }
            "response" : { 
                "status" : "200",
                "success": "true",
                "message": "successful",
                "error" : [{}]
                },
        },
        

### Drop Rider [Put]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
+ Request (application/json)

        {
            "user_id":"442355",
            "trip_id":"dsgid",
            "host_id" : "4a6sd46asd46",
            "status" : "dropped"
        }

+ Response 200 (application/json)

   

    + Body

           {
           
                "data" : {
                    "trip_member" : 
                    {
                        "user_id" : "4fewr6",
                        "full_name" : "hasan",
                        "profile_pic" : "url",
                        "fare" : 45
                    },
                },
                "response" : { 
                    "status" : "200",
                    "success": "true",
                    "message": "User has been dropped",
                    "error" : [{}]
                    }
           }
 
 
 
 
### View Favourites [Get]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
            "user_id": "s23-234-234-234"
        }

+ Response 200 (application/json)

   

    + Body

            {
                "data" : {
                    "favorites" : [
                        { 
                            "favorites_id" : 2342,
                            "name" : "Work",
                            "location" : "30.23423/23.23434",
                            "location_name" : "Brac IT Services"
                        },
                        { 
                            "favorites_id" : 2342,
                            "name" : "Home",
                            "location" : "30.23423/23.23434",
                            "location_name" : "agargaon"
                        },
                        { 
                            "favorites_id" : 2342,
                            "name" : "AIUB",
                            "location" : "30.23423/23.23434",
                            "location_name" : "American International University Bangladesh"
                        }
                    ],
                }
                "response" : { 
                    "status" : "200",
                    "success": "true",
                    "message": "successful",
                    "error" : [{}]
                }
            }
            
### Add Favourites [Post]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
            "user_id": "s23-234-234-234",
            "favorites" : { 
                    "name" : "Work",
                    "location" : "30.23423/23.23434",
                    "location_name" : "Brac IT Services"
                },
        }

+ Response 200 (application/json)

   

    + Body

            {
                "data": {
                    "favorites" : { 
                        "favorites_id" : 2342,
                        "name" : "Work",
                        "location" : "30.23423/23.23434",
                        "location_name" : "Brac IT Services"
                    },
                }
                "response" : { 
                    "status" : "200",
                    "success": "true",
                    "message": "New fovourite place has been added",
                    "error" : [{}]
            }
            

+ Response 409 (application/json)

   

    + Body

            {
                "data" : {}
                "response" : { 
                    "status" : "409",
                    "success": "false",
                    "message": "Conflict",
                    "error" : [{
                    "message" : "Name Already Exists"
                    }]
            }
            

### Update Favourites [Put]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
            "user_id": "s23-234-234-234",
            "favorites" : { 
                    "favorites_id" : 2342,
                    "name" : "Work",
                    "location" : "30.23423/23.23434",
                    "location_name" : "Brac IT Services"
                }
        }

+ Response 200 (application/json)

   

    + Body

            {

                "data" : {
                    "favorites" : {
                        "favorites_id" : 2342,
                        "name" : "Work",
                        "location" : "30.23423/23.23434",
                        "location_name" : "Brac IT Services"
                    },
                }
                "response" : { 
                    "status" : "200",
                    "success": "true",
                    "message": "successful",
                    "error" : [{}]
                }
            }


+ Response 409 (application/json)

   

    + Body

            {
                
                "data" : {
                    "favorites" : { 
                        "name" : "Work",
                        "location" : "30.23423/23.23434",
                        "location_name" : "Brac IT Services"
                    },
                }
                "response" : { 
                    "status" : "409",
                    "success": "false",
                    "message": "Conflict",
                    "error" : [{
                    "message" : "Name Already Exists"
                    }]
            }
            

### View Companies [Get]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

    {
    "user_id": "s23-234-234-234",
    }

+ Response 200 (application/json)

   

    + Body

            {
                "data" : [
                    { 
                        "company_id" : "2343",
                        "company_name" : "Brac Bank Ltd.",
                        "address" : "Anik Tower Niketan",
                        "location" : "lat/lon",
                        "phone_number" : "014897979",
                        "verified" : "true"
                    },
                    { 
                        "company_id" : "4356",
                        "company_name" : "Brac IT Services",
                         "address" : "Anik Tower Niketan",
                        "location" : "lat/lon",
                        "phone_number" : "014897979",
                        "verified" : "true"
                    }
                ],
                "response" : { 
                    "status" : "200",
                    "success": "true",
                    "message": "Successful",
                    "error" : [{}]
            }
            
//Completed till here


### Add a Company [Post]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
            "company_id" : "4dfe6d46w",
           "user_id" : "d4s64dwq"
        }

+ Response 200 (application/json)

   

    + Body

            {
                "data" :{
                "company" : [{
                 "company_name" : "Brac Bank Ltd.",
                 "company_id" : "dailejw",
                    "phone_number" : 01676868564,
                    "address" : "34/A niketan, dhaka",
                    "location" : "30.23423/23.23434",
                    "company_email" : "bits@bracits.com"
                }],
                   
                },
                "response" : { 
                    "status" : "200",
                    "success": "true",
                    "message": "Successful",
                    "error" : [{}]
                }
            }
            
### View Pending Friend Request [Get]

Here user will see the list of pending friends request

+ Headers 
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
            "user_id" : "2637"
        }
        
+ Response 200 (application/json)

    + Body
    
            {
                "data": {
                    "friends" : [{
                                "from":"d56qwe6wq",
                                "to":"46qwe4qw",
                                "status":"pending",
                            
                            "mutual_friends": [
                            {
                                "user_id" : "4as56d46aw"
                                "full_name": "raju mazumder"
                                }
                            ],
                            
                            }],
                           "response" : { 
                    "status" : "200",
                    "success": "true",
                    "message": "Successful",
                    "error" : [{}]       
                        
                    
                        
            }

### Email varification [Post]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
            "email" : "sdad@gmail.com",
            "user_id" : "e4r6w4e"

        }

+ Response 200 (application/json)

   

    + Body

            {
                "data" :{},
                "response" : {
                    "status" : 200,
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                }
            }

+ Response 400 (application/json)

   

    + Body

            {
                "data" :{},

                "response" : {
                    "status" : 400,
                    "message" : "Bad Request",
                    "success" : "true",
                    "error" : [{
                    "message" : "emain syntax error"
                    }]
                }
            }
+ Response 409 (application/json)

   

    + Body

            {
                "data" :{},

                "response" : {
                    "status" : 400,
                    "message" : "Conflict",
                    "success" : "true",
                    "error" : [{
                    "message" : "Email Already Exists"
                    }]
                }
            }


[Admin]
### Edit Company [Post]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
            "company_name" : "mycom",
            "phone_number" : "0178764546",
            "address" : "somewhere",
            "location" : "lat/lon",
            "company_email" : "sdad@gmail.com",
            "verified" : "2"
            
        }

+ Response 200 (application/json)

   

    + Body

            {
                "data" :{},
                "response" : {
                    "status" : 200,
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                }
            }

[Admin]
### Delete company[Delete] 

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
           "company_id" : "d485a47d6as"
            
        }

+ Response 200 (application/json)

   

    + Body

            {
                "data" :{},
                "response" : {
                    "status" : 200,
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                }
            }

### View Languages[Get]


+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
           "user_id" : "d485a47d6as"
            
        }

+ Response 200 (application/json)

   

    + Body

            {
                "data" :{
                "languages" : [
                {"BN"},{"EN"},{"FR"},
                ]
                },
                "response" : {
                    "status" : 200,
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                }
            }
///what to return 
### Send friend request[Post]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
           "from_id" : "d485a47d6as"
            "to_id" : "4dsa89d78sa"
            "status" : "1"
        }

+ Response 200 (application/json)

   

    + Body

            {
                "data" :{},
                "response" : {
                    "status" : 200,
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                }
            }

+ Response 401 (application/json)

   

    + Body

            {
                "data" :{},
                "response" : {
                    "status" : 401,
                    "message" : "Unauthorized",
                    "success" : "false",
                    "error" : [{
                    "message" : "Can not send friend rquest"}]
                }
            }


### Accept/Block/unblock/unfriend friend [Post]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
           "from_id" : "d485a47d6as"
            "to_id" : "4dsa89d78sa"
            "status" : "1"
        }

+ Response 200 (application/json)

   

    + Body

            {
                "data" :{},
                "response" : {
                    "status" : 200,
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                }
            }


+ Response 409 (application/json)

   

    + Body

            {
                "data" :{},
                "response" : {
                    "status" : 409,
                    "message" : "Conflict",
                    "success" : "false",
                    "error" : [{
                    "message" : "Request already processed"
                    }]
                }
            }


### View Friend request[Get]

+ Headers
    {
        "api_key" : "Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
           "user_id" : "d485a47d6as"
           
            "status" : "1"
        }

+ Response 200 (application/json)

   

    + Body

            {
                "data" :{
                "friend" [
                {"from" : "myid",
                "to" : "djwjeowi"
                },
                {"from" : "myid",
                "to" : "djwjeowi"
                },
                {"from" : "myid",
                "to" : "djwjeowi"
                }
                ]
                },
                "response" : {
                    "status" : 200,
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                }
            }


### Report[post]

+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
           "from_id" : "d485a47d6as",
           "to_id",
           
            "report_message" : "abusive language"
        }

+ Response 200 (application/json)

   

    + Body

            {
                
                "response" : {
                    "status" : 200,
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                }
            }

### View Search history[Get]


+ Headers
    {
        "api_key":"Token dgsdgdsgds"
    }
    
+ Request (application/json)

        {
           "user_id" : "d485a47d6as",
          
            "search_query" : "takeout"
        }

+ Response 200 (application/json)

   

    + Body

            {
                "data" : {
                "user_search_history" : [
                {
                "source_location_name" : "niketon",
                "source_locaation" : "lat/lon",
                "destination_location_name" : "jamunafuture"
                "destination_location" : "lat/lon" 
                }
                ]},
                "response" : {
                    "status" : 200,
                    "message" : "Successful",
                    "success" : "true",
                    "error" : [{}]
                }
            }